/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.controller.BookController;
import edu.ijse.controller.BorrowingTransactionsController;
import edu.ijse.controller.MemberController;
import edu.ijse.controller.ReturnController;

import edu.ijse.dto.BookDto;
import edu.ijse.dto.MemberDto;
import edu.ijse.dto.ReturnDetailDto;
import edu.ijse.dto.ReturnDto;
import edu.ijse.homePage.homePage;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ReturnView extends javax.swing.JFrame {
   private MemberController memberController;
    private BookController bookController;
     private ReturnController returnController;
    private BorrowingTransactionsController borrowingTransactionsController;
    private ArrayList<ReturnDetailDto> returnDetailDtos = new ArrayList<>();
    /**
     * Creates new form ReturnView
     */
    public ReturnView() {
         this.memberController = new MemberController();
        this.bookController = new BookController();
        this.borrowingTransactionsController = new BorrowingTransactionsController();
        this.returnController = new ReturnController();
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
           loadTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtFine = new javax.swing.JTextField();
        lblFine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMemberSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblMemberData = new javax.swing.JTextArea();
        lblBookId = new javax.swing.JLabel();
        btnBookSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblBookData = new javax.swing.JTextArea();
        lblMemberId = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtMemberId = new javax.swing.JTextField();
        javax.swing.JLabel lblReturnId = new javax.swing.JLabel();
        txtBorrowingId = new javax.swing.JTextField();
        txtReturnId = new javax.swing.JTextField();
        lblBorrowingID = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        btnBorrowingIdSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblBorrowingData = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        txtQty = new javax.swing.JTextField();
        btnPlace = new javax.swing.JButton();
        txtBookId = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTopic.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTopic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic.setText("Return & Apply Fines");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFine.setText("Apply Fines");

        btnMemberSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMemberSearch.setText("Search");
        btnMemberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberSearchActionPerformed(evt);
            }
        });

        lblMemberData.setColumns(20);
        lblMemberData.setRows(5);
        jScrollPane1.setViewportView(lblMemberData);

        lblBookId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBookId.setText("Book ID");

        btnBookSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBookSearch.setText("Search");
        btnBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSearchActionPerformed(evt);
            }
        });

        lblBookData.setColumns(20);
        lblBookData.setRows(5);
        jScrollPane3.setViewportView(lblBookData);

        lblMemberId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemberId.setText("Member ID");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblReturnId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReturnId.setText("Return ID");

        txtBorrowingId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrowingIdActionPerformed(evt);
            }
        });

        lblBorrowingID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBorrowingID.setText("Boorowing ID");

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setText("Quantity");

        btnBorrowingIdSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrowingIdSearch.setText("Search");
        btnBorrowingIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowingIdSearchActionPerformed(evt);
            }
        });

        lblBorrowingData.setColumns(20);
        lblBorrowingData.setRows(5);
        jScrollPane2.setViewportView(lblBorrowingData);

        btnPlace.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlace.setText("Place");
        btnPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceActionPerformed(evt);
            }
        });

        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReturnMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblReturn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberId)
                            .addComponent(lblQty)
                            .addComponent(btnMemberSearch)
                            .addComponent(lblReturnId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBorrowingId, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 68, Short.MAX_VALUE)
                                .addComponent(btnBorrowingIdSearch)
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBookSearch)
                                    .addComponent(lblBookId))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBorrowingID)
                        .addGap(69, 69, 69)
                        .addComponent(txtReturnId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFine)
                        .addGap(85, 85, 85)
                        .addComponent(txtFine, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(btnAdd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addComponent(btnPlace)
                        .addGap(35, 35, 35)
                        .addComponent(btnBack)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReturnId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBorrowingID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBorrowingIdSearch)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBorrowingId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblReturnId))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberId)
                    .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookId)
                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnMemberSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBookSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFine)
                            .addComponent(txtFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPlace)
                                .addComponent(btnBack)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(149, 149, 149))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      setVisible(false);
        new homePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMemberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberSearchActionPerformed
        searchMember();
    }//GEN-LAST:event_btnMemberSearchActionPerformed

    private void btnBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSearchActionPerformed
        searchBook();
    }//GEN-LAST:event_btnBookSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtBorrowingIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrowingIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorrowingIdActionPerformed

    private void btnBorrowingIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowingIdSearchActionPerformed
      searchBorrow();
    }//GEN-LAST:event_btnBorrowingIdSearchActionPerformed

    private void btnPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceActionPerformed
Place();   
    }//GEN-LAST:event_btnPlaceActionPerformed

    private void tblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReturnMouseClicked
    }//GEN-LAST:event_tblReturnMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookSearch;
    private javax.swing.JButton btnBorrowingIdSearch;
    private javax.swing.JButton btnMemberSearch;
    private javax.swing.JButton btnPlace;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea lblBookData;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JTextArea lblBorrowingData;
    private javax.swing.JLabel lblBorrowingID;
    private javax.swing.JLabel lblFine;
    private javax.swing.JTextArea lblMemberData;
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JTable tblReturn;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBorrowingId;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReturnId;
    // End of variables declaration//GEN-END:variables
public void searchMember() {
        try {
            String memberId = txtMemberId.getText();
            MemberDto  memberDto =  memberController.get( memberId);
            if ( memberDto != null) {
                lblMemberData.setText( memberDto.getTitle() + " " +  memberDto.getName() + " | " +  memberDto.getAddress());
            } else {
                lblMemberData.setText("Member Not Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchBook() {
        try {
            String bookId = txtBookId.getText();
            BookDto bookDto = bookController.get(bookId);
            if (bookDto != null) {
                lblBookData.setText(bookDto.getName() + " | " + bookDto.getAuthor()+ " | " + bookDto.getnumber() + " | " + bookDto.getPrice());
            } else {
                lblBookData.setText("Book Not Found");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void addToTable() {
       ReturnDetailDto returnDetailDto=new ReturnDetailDto();
        returnDetailDto.setBookId(txtBookId.getText());
        returnDetailDto.setQty(Integer.parseInt(txtQty.getText()));
        
      
                returnDetailDtos.add(returnDetailDto);

        Object[] rowData={returnDetailDto.getBookId(),returnDetailDto.getQty()};
        DefaultTableModel dtm=(DefaultTableModel)tblReturn.getModel();
        dtm.addRow(rowData);
        
        clear();
    }
    
    private void clear(){
       txtBookId.setText("");
       txtQty.setText("");
       lblMemberData.setText("");
    }
    
    private void loadTable(){

        String columns[]={"Book Id","Qty"};
        DefaultTableModel dtm =new DefaultTableModel(columns,0){
          public boolean  isCellEditable(int row,int column){
              return false;
          }  
        };
        tblReturn.setModel(dtm);
        
    }
    
    

    private void Place() {
        try{
            ReturnDto returnDto=new ReturnDto();
            returnDto.setMemberId(txtMemberId.getText());
            returnDto.setReturnId(txtReturnId.getText());
            
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(new Date());
            returnDto.setDate(date);          
           
            returnDto.setReturnDetailDtos(returnDetailDtos);
            
            returnDto.setFine(Double.parseDouble(txtFine.getText()));
            
            String resp=returnController.Place(returnDto);
            JOptionPane.showMessageDialog(this,resp);
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
     private void searchBorrow(){
        try{
                  
              String id=txtReturnId.getText();
              String borrow=borrowingTransactionsController.gets(id);
              if(borrow!=null){
                  lblBorrowingData.setText(borrow);                       
        
    String returnDateString = lblBorrowingData.getText();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    LocalDate returnDate = LocalDate.parse(returnDateString, formatter);
    LocalDate currentDate = LocalDate.now();
    long daysBetween = ChronoUnit.DAYS.between(returnDate, currentDate);
    double fine ;
    if(daysBetween<=14){
        fine=0;
    }else{
         fine = (daysBetween-14) * 5;
    }
txtFine.setText(String.valueOf(fine));
                  
              }else{
                  lblBorrowingData.setText("Book can not found");
              }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
     
}

